MVC/MVC/Models/Bookmark/CreateEditBookmarkViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Protocols;

namespace MVC.Models.Bookmark
{
    public class CreateEditBookmarkViewModel
    {
        public CreateEditBookmarkViewModel()
        {
            Categories = new List<SelectListItem>();
        }
        public int Id { get; set; }

        [StringLength(maximumLength: 500)]
        [Required(ErrorMessage = "The url is required")]
        public string URL { get; set; }
        [Display(Name = "Short Description")]
        public string ShortDescription { get; set; }
        public int? CategoryId { get; set; }
        public List<SelectListItem> Categories { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}

MVC/MVC/Models/Bookmark/ListBookmarksViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC.Models.Bookmark
{
    public class ListBookmarksViewModel
    {
        public ListBookmarksViewModel()
        {

        }
        public int Id { get; set; }
        public string Url { get; set; }

        [Display(Name = "Short Description")]
        public string ShortDescription { get; set; }
        public string Category { get; set; }
    }
}

MVC/MVC/Controllers/BookmarkController.cs
using Microsoft.AspNet.Identity;
using MVC.Models.Bookmark;
using ReadLater.Entities;
using ReadLater.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    [Authorize]
    public class BookmarkController : Controller
    {
        IBookmarkService _bookmarkService;
        ICategoryService _categoryService;
        public BookmarkController(IBookmarkService bookmarkService, ICategoryService categoryService)
        {
            _bookmarkService = bookmarkService;
            _categoryService = categoryService;
        }
        // GET: Bookmark
        public ActionResult Index()
        {
            return View();
        }
     
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                //Automapper missing or modelBinding like in category controller
                var model = new CreateEditBookmarkViewModel();
                var categories = _categoryService.GetCategories();
                model.Categories = categories.Select(x =>
                                  new SelectListItem()
                                  {
                                      Text = x.Name,
                                      Value = x.ID.ToString()
                                  }).ToList();

                return View(model);
            }
            catch (Exception)
            {

                throw;
            } 
        }
    
        [HttpPost]
        public ActionResult CreateConfirmed(CreateEditBookmarkViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Automapper missing
                    var bookmark = new Bookmark();
                    bookmark.CreatedBy = User.Identity.GetUserId();
                    bookmark.URL = model.URL;
                    bookmark.CategoryId = model.CategoryId;
                    bookmark.ShortDescription = model.ShortDescription;
                    _bookmarkService.CreateBookmark(bookmark);
                    return RedirectToAction("Bookmarks");
                }
                return View(model);
       
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public ActionResult Bookmarks()
        {
            try
            {
                
                var bookmarks = _bookmarkService.GetBookmarks(string.Empty);
                //Automapper missing
                var model = new List<ListBookmarksViewModel>();
                foreach(var bookmrk in bookmarks)
                {
                    model.Add(new ListBookmarksViewModel()
                    {
                        Category = bookmrk.Category?.Name,
                        Id = bookmrk.ID,
                       ShortDescription = bookmrk.ShortDescription,
                       Url = bookmrk.URL
                    }); ;
                }
                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpGet]
        public ActionResult Edit(int bookmarkId)
        {
            try
            {
                //Automapper missing
                var bookmark = _bookmarkService.GetBookMarkById(bookmarkId);
                var model = new CreateEditBookmarkViewModel() { 
                    Id = bookmark.ID,
                    CategoryId = bookmark.CategoryId,
                    ShortDescription = bookmark.ShortDescription,
                    URL = bookmark.URL,
                    CreatedBy = bookmark.CreatedBy,
                    DateCreated = bookmark.CreateDate
                };
                var categories = _categoryService.GetCategories();
                model.Categories = categories.Select(x =>
                                new SelectListItem()
                                {
                                    Text = x.Name,
                                    Value = x.ID.ToString()
                                }).ToList();
                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public ActionResult EditConfirmed(CreateEditBookmarkViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Automapper missing
                    var bookmark = new Bookmark()
                    {
                        ID = model.Id,
                        CategoryId = model.CategoryId,
                        URL = model.URL,
                        ShortDescription = model.ShortDescription,
                        CreateDate = model.DateCreated,
                        CreatedBy = model.CreatedBy,
                        ObjectState = ObjectState.Modified
                    };
                    _bookmarkService.UpdateBookmark(bookmark);
                    return RedirectToAction("Bookmarks");
                }
                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

MVC/MVC/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReadLater.Data;
using ReadLater.Entities;
using ReadLater.Services;

namespace MVC.Controllers
{
    public class CategoriesController : Controller
    {
        ICategoryService _categoryService;
        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        // GET: Categories
        public ActionResult Index()
        {
            List<Category> model = _categoryService.GetCategories();
            return View(model);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = _categoryService.GetCategory((int)id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);

        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.CreateCategory(category);
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = _categoryService.GetCategory((int)id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.UpdateCategory(category);
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = _categoryService.GetCategory((int)id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = _categoryService.GetCategory(id);
            _categoryService.DeleteCategory(category);
            return RedirectToAction("Index");
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult CreateCategoryAsync(string categoryName)
        {
            if (!String.IsNullOrEmpty(categoryName))
            {
                var cat = new Category() { Name = categoryName, ObjectState = ObjectState.Added };    
                _categoryService.CreateCategory(cat);
                return Json(cat);
            }
            else
                return Json("error");
        }
    }
}

MVC/MVC/Views/Bookmark/Bookmarks.cshtml
@model IEnumerable<MVC.Models.Bookmark.ListBookmarksViewModel>

@{
    ViewBag.Title = "Bookmarks";
}

<h2>Bookmarks</h2>

<p>
    @Html.ActionLink("Create New", "Create","Bookmark",null,null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { bookmarkId = item.Id }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.Id }) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVC/MVC/Views/Bookmark/Create.cshtml
@model MVC.Models.Bookmark.CreateEditBookmarkViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Bookmark</h2>


@using (Html.BeginForm("CreateConfirmed", "Bookmark", FormMethod.Post, new { @class = "create-bookmark-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoryId,Model.Categories)
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Create new category</button>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Category</h4>
            </div>
            <div class="modal-body">
                <p>Category Name: </p>
                <input type="text" id="categoryNameInputField"/>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-default" id="addNewCategory">Create</button>
            </div>
        </div>

    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@*THIS SHOULD GO TO A SEPARATE SCRIPT file and the script should be included here, or in bundle*@
<script>
    $('#addNewCategory').on('click', function () {
          $.ajax({
            url: "@Url.Action("CreateCategoryAsync", "Categories")",
            type: "POST",
              data: {
                  categoryName: $('#categoryNameInputField').val() },
              success: function (data) {
                  debugger;
                if (data != "error") {
                    debugger;
                    $('#CategoryId').append($('<option/>', {
                        value: data.ID,
                        text: data.Name
                    }));

                    $('#CategoryId option[value="'+ data.ID +'"]').attr("selected", "selected");
                    $('#myModal').modal("hide");
                }
            },
            error: function (data) {

            }
        });



    })
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/MVC/Views/Bookmark/Edit.cshtml
@model MVC.Models.Bookmark.CreateEditBookmarkViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Bookmark</h2>


@using (Html.BeginForm("EditConfirmed", "Bookmark", FormMethod.Post, new { @class = "create-bookmark-form" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.DateCreated)

    <div class="form-group">
        @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.CategoryId, Model.Categories)
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}